name: Sonar Sample

on:
  push:
    branches:
      - raghib

jobs:
  build:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: test
      run: |
          Copy-Item  -Path .\sonarqube-scanner-ant\ant-basic\lib\sonarqube-ant-task-2.7.0.1612.jar -Destination C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-1.10.12\lib
          echo ${{ secrets.SONAR_TOKEN }}
    - name: Build with Ant
      run: |
          cd sonarqube-scanner-ant/ant-basic/
          ant all -Dsonar.login=squ_c82b81bbecf40c9a2cd55573a7d3408f606d847f